export = readability;
declare const readability: Readability;
declare class Readability {
    static getGradeSuffix(grade: any): any;
    static split(text: any): any;
    charCount(text: any, ignoreSpaces?: boolean): any;
    letterCount(text: any, ignoreSpaces?: boolean): any;
    removePunctuation(text: any): any;
    lexiconCount(text: any, removePunctuation?: boolean): any;
    syllableCount(text: any, lang?: string): any;
    sentenceCount(text: any): number;
    averageSentenceLength(text: any): any;
    averageSyllablePerWord(text: any): any;
    averageCharacterPerWord(text: any): any;
    averageLetterPerWord(text: any): any;
    averageSentencePerWord(text: any): any;
    fleschReadingEase(text: any): any;
    fleschReadingEaseToGrade(score: any): 5 | 6 | 7 | 8.5 | 11 | 13 | 15 | 16;
    fleschKincaidGrade(text: any): any;
    polySyllableCount(text: any): number;
    smogIndex(text: any): any;
    colemanLiauIndex(text: any): any;
    automatedReadabilityIndex(text: any): any;
    linsearWriteFormula(text: any): number;
    presentTense(word: any): any;
    difficultWords(text: any, syllableThreshold?: number): number | Set<any>;
    daleChallReadabilityScore(text: any): any;
    daleChallToGrade(score: any): 5 | 7 | 11 | 13 | 16 | 4 | 9;
    gunningFog(text: any): any;
    lix(text: any): any;
    rix(text: any): any;
    textStandard(text: any, floatOutput?: any): any;
    textMedian(text: any): any;
}
